
import type { Project } from '@/types/project';

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'Phoenix Initiative',
    status: 'On Track',
    description: 'A revolutionary new platform to integrate all enterprise services into a unified dashboard.',
    startDate: '2024-01-15',
    endDate: '2024-12-20',
    budget: 500000,
    spent: 120000,
    completionPercentage: 25,
    teamLead: 'Alice Wonderland',
    keyMilestones: [
      { id: 'm1-1', name: 'Initial Design Phase Complete', date: '2024-03-01', status: 'Completed' },
      { id: 'm1-2', name: 'Alpha Version Release', date: '2024-06-15', status: 'In Progress' },
      { id: 'm1-3', name: 'Beta Testing', date: '2024-09-01', status: 'Pending' },
    ],
    lastUpdated: '2024-07-20',
    priority: 'High',
    portfolio: 'Core Infrastructure',
    riskAssessment: undefined, 
  },
  {
    id: 'proj-002',
    name: 'Orion Data Migration',
    status: 'At Risk',
    description: 'Migrate legacy customer data to the new cloud infrastructure with zero downtime.',
    startDate: '2024-03-01',
    endDate: '2024-09-30',
    budget: 250000,
    spent: 180000,
    completionPercentage: 60,
    teamLead: 'Bob The Builder',
    keyMilestones: [
      { id: 'm2-1', name: 'Infrastructure Setup', date: '2024-04-01', status: 'Completed' },
      { id: 'm2-2', name: 'Test Data Migration', date: '2024-06-01', status: 'Completed' },
      { id: 'm2-3', name: 'Production Data Migration Window 1', date: '2024-08-15', status: 'Blocked' },
    ],
    lastUpdated: '2024-07-18',
    priority: 'High',
    portfolio: 'Core Infrastructure',
    riskAssessment: { 
        identifiedRisks: ["Potential data loss during migration", "Unexpected downtime exceeding SLA"],
        riskMitigationRecommendations: ["Perform incremental backups before migration", "Have rollback plan ready"],
        overallRiskScore: 75,
    }
  },
  {
    id: 'proj-003',
    name: 'Nebula AI Integration',
    status: 'Delayed',
    description: 'Integrate a third-party AI module for advanced analytics into the existing CRM.',
    startDate: '2024-02-01',
    endDate: '2024-07-31',
    budget: 150000,
    spent: 140000,
    completionPercentage: 85,
    teamLead: 'Carol Danvers',
    keyMilestones: [
      { id: 'm3-1', name: 'API Key Acquisition', date: '2024-02-15', status: 'Completed' },
      { id: 'm3-2', name: 'Core Module Integration', date: '2024-05-01', status: 'Completed' },
      { id: 'm3-3', name: 'User Acceptance Testing', date: '2024-07-15', status: 'In Progress' },
    ],
    lastUpdated: '2024-07-15',
    priority: 'Medium',
    portfolio: 'Customer Experience',
    riskAssessment: undefined,
  },
  {
    id: 'proj-004',
    name: 'Titan Security Overhaul',
    status: 'Completed',
    description: 'Comprehensive upgrade of all internal security protocols and systems.',
    startDate: '2023-09-01',
    endDate: '2024-03-31',
    budget: 300000,
    spent: 285000,
    completionPercentage: 100,
    teamLead: 'David Copperfield',
    keyMilestones: [
      { id: 'm4-1', name: 'System Audit', date: '2023-10-01', status: 'Completed' },
      { id: 'm4-2', name: 'Protocol Implementation', date: '2024-01-15', status: 'Completed' },
      { id: 'm4-3', name: 'Final Review & Sign-off', date: '2024-03-20', status: 'Completed' },
    ],
    lastUpdated: '2024-04-01',
    priority: 'High',
    portfolio: 'Core Infrastructure',
    riskAssessment: {
        identifiedRisks: ["Initial vulnerabilities identified in audit"],
        riskMitigationRecommendations: ["All identified vulnerabilities patched and verified"],
        overallRiskScore: 15,
    }
  },
   {
    id: 'proj-005',
    name: 'Nova Mobile App',
    status: 'Planning',
    description: 'Develop a new cross-platform mobile application for customer engagement.',
    startDate: '2024-08-01',
    endDate: '2025-02-28',
    budget: 400000,
    spent: 10000,
    completionPercentage: 5,
    teamLead: 'Eva Green',
    keyMilestones: [
      { id: 'm5-1', name: 'Market Research', date: '2024-08-30', status: 'In Progress' },
      { id: 'm5-2', name: 'UX/UI Design Specs', date: '2024-10-15', status: 'Pending' },
    ],
    lastUpdated: '2024-07-19',
    priority: 'Medium',
    portfolio: 'Innovation Lab',
    riskAssessment: undefined,
  },
  {
    id: 'proj-006',
    name: 'Apollo Marketing Campaign',
    status: 'On Track',
    description: 'Launch a new marketing campaign for the Q4 product release.',
    startDate: '2024-07-01',
    endDate: '2024-10-31',
    budget: 120000,
    spent: 30000,
    completionPercentage: 20,
    teamLead: 'Frank Moses',
    keyMilestones: [
      { id: 'm6-1', name: 'Campaign Strategy Finalized', date: '2024-07-15', status: 'Completed' },
      { id: 'm6-2', name: 'Creative Assets Production', date: '2024-08-30', status: 'In Progress' },
      { id: 'm6-3', name: 'Campaign Launch', date: '2024-10-01', status: 'Pending' },
    ],
    lastUpdated: '2024-07-22',
    priority: 'Medium',
    portfolio: 'Customer Experience',
    riskAssessment: undefined,
  },
  // New Projects Start Here
  {
    id: 'proj-007',
    name: 'Quantum Leap Platform',
    status: 'Planning',
    description: 'Next-generation computing platform research and development.',
    startDate: '2024-09-01',
    endDate: '2026-08-31',
    budget: 1200000,
    spent: 50000,
    completionPercentage: 2,
    teamLead: 'Grace Hopper',
    keyMilestones: [
      { id: 'm7-1', name: 'Feasibility Study', date: '2024-11-30', status: 'Pending' },
      { id: 'm7-2', name: 'Prototype Design', date: '2025-03-31', status: 'Pending' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'High',
    portfolio: 'Research & Development',
  },
  {
    id: 'proj-008',
    name: 'CyberGuard Initiative',
    status: 'On Track',
    description: 'Enhance enterprise-wide cybersecurity posture against emerging threats.',
    startDate: '2024-05-15',
    endDate: '2025-01-31',
    budget: 350000,
    spent: 90000,
    completionPercentage: 30,
    teamLead: 'Harry Dresden',
    keyMilestones: [
      { id: 'm8-1', name: 'Threat Modeling', date: '2024-07-01', status: 'Completed' },
      { id: 'm8-2', name: 'Firewall Upgrades', date: '2024-09-15', status: 'In Progress' },
    ],
    lastUpdated: '2024-07-24',
    priority: 'High',
    portfolio: 'Security Operations',
  },
  {
    id: 'proj-009',
    name: 'EcoOptimize Supply Chain',
    status: 'At Risk',
    description: 'Optimize supply chain logistics for reduced carbon footprint and cost savings.',
    startDate: '2024-04-01',
    endDate: '2024-11-30',
    budget: 200000,
    spent: 150000,
    completionPercentage: 55,
    teamLead: 'Ivy Valentine',
    keyMilestones: [
      { id: 'm9-1', name: 'Current State Analysis', date: '2024-05-15', status: 'Completed' },
      { id: 'm9-2', name: 'Vendor Negotiations', date: '2024-08-01', status: 'Blocked' },
    ],
    lastUpdated: '2024-07-23',
    priority: 'Medium',
    portfolio: 'Sustainability Goals',
  },
  {
    id: 'proj-010',
    name: 'Zenith HR Portal',
    status: 'Delayed',
    description: 'Develop a new self-service portal for Human Resources.',
    startDate: '2024-01-10',
    endDate: '2024-08-30',
    budget: 180000,
    spent: 170000,
    completionPercentage: 90,
    teamLead: 'Jack Sparrow',
    keyMilestones: [
      { id: 'm10-1', name: 'Requirements Gathering', date: '2024-02-28', status: 'Completed' },
      { id: 'm10-2', name: 'Backend Development', date: '2024-06-15', status: 'Completed' },
      { id: 'm10-3', name: 'Frontend Polish', date: '2024-08-10', status: 'In Progress' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'Low',
    portfolio: 'Internal Tools',
  },
  {
    id: 'proj-011',
    name: 'Vortex VR Training',
    status: 'Completed',
    description: 'Create VR training modules for new employee onboarding.',
    startDate: '2023-10-01',
    endDate: '2024-05-31',
    budget: 220000,
    spent: 215000,
    completionPercentage: 100,
    teamLead: 'Kara Thrace',
    keyMilestones: [
      { id: 'm11-1', name: 'Scenario Design', date: '2023-11-15', status: 'Completed' },
      { id: 'm11-2', name: 'VR Development', date: '2024-03-01', status: 'Completed' },
      { id: 'm11-3', name: 'Pilot Program', date: '2024-05-01', status: 'Completed' },
    ],
    lastUpdated: '2024-06-05',
    priority: 'Medium',
    portfolio: 'Innovation Lab',
  },
  {
    id: 'proj-012',
    name: 'Matrix Data Lakehouse',
    status: 'On Track',
    description: 'Build a centralized data lakehouse for advanced analytics and reporting.',
    startDate: '2024-06-01',
    endDate: '2025-03-31',
    budget: 600000,
    spent: 75000,
    completionPercentage: 15,
    teamLead: 'Luke Skywalker',
    keyMilestones: [
      { id: 'm12-1', name: 'Data Source Identification', date: '2024-07-31', status: 'In Progress' },
      { id: 'm12-2', name: 'Schema Design', date: '2024-09-30', status: 'Pending' },
    ],
    lastUpdated: '2024-07-22',
    priority: 'High',
    portfolio: 'Data & Analytics',
  },
  {
    id: 'proj-013',
    name: 'Helios Solar Farm Integration',
    status: 'Planning',
    description: 'Integrate new solar farm output into the existing power grid.',
    startDate: '2024-10-01',
    endDate: '2025-06-30',
    budget: 750000,
    spent: 20000,
    completionPercentage: 3,
    teamLead: 'Maria Hill',
    keyMilestones: [
      { id: 'm13-1', name: 'Regulatory Approval', date: '2024-12-15', status: 'Pending' },
      { id: 'm13-2', name: 'Grid Connection Study', date: '2025-02-28', status: 'Pending' },
    ],
    lastUpdated: '2024-07-19',
    priority: 'High',
    portfolio: 'Sustainability Goals',
  },
  {
    id: 'proj-014',
    name: 'Aegis Compliance Audit Tool',
    status: 'On Track',
    description: 'Develop an automated tool for continuous compliance auditing.',
    startDate: '2024-03-15',
    endDate: '2024-10-31',
    budget: 190000,
    spent: 100000,
    completionPercentage: 50,
    teamLead: 'Nick Fury',
    keyMilestones: [
      { id: 'm14-1', name: 'Framework Definition', date: '2024-05-01', status: 'Completed' },
      { id: 'm14-2', name: 'Rule Engine Development', date: '2024-08-15', status: 'In Progress' },
    ],
    lastUpdated: '2024-07-24',
    priority: 'Medium',
    portfolio: 'Security Operations',
  },
  {
    id: 'proj-015',
    name: 'Odyssey Customer Journey Mapping',
    status: 'At Risk',
    description: 'Map and optimize the end-to-end customer journey across all touchpoints.',
    startDate: '2024-05-01',
    endDate: '2024-12-15',
    budget: 90000,
    spent: 70000,
    completionPercentage: 40,
    teamLead: 'Olivia Dunham',
    keyMilestones: [
      { id: 'm15-1', name: 'Workshop Facilitation', date: '2024-06-30', status: 'Completed' },
      { id: 'm15-2', name: 'Data Collection from Systems', date: '2024-09-01', status: 'Blocked' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'Medium',
    portfolio: 'Customer Experience',
  },
  {
    id: 'proj-016',
    name: 'Pathfinder R&D Automation',
    status: 'On Track',
    description: 'Automate repetitive tasks in the R&D lab environment.',
    startDate: '2024-02-01',
    endDate: '2024-09-30',
    budget: 280000,
    spent: 150000,
    completionPercentage: 65,
    teamLead: 'Peter Bishop',
    keyMilestones: [
      { id: 'm16-1', name: 'Process Identification', date: '2024-03-15', status: 'Completed' },
      { id: 'm16-2', name: 'Robotics Integration', date: '2024-07-31', status: 'In Progress' },
    ],
    lastUpdated: '2024-07-20',
    priority: 'Medium',
    portfolio: 'Research & Development',
  },
  {
    id: 'proj-017',
    name: 'Catalyst Partner Portal',
    status: 'Completed',
    description: 'Launch a new portal for B2B partners with enhanced features.',
    startDate: '2023-11-01',
    endDate: '2024-06-30',
    budget: 320000,
    spent: 310000,
    completionPercentage: 100,
    teamLead: 'Quinn Fabray',
    keyMilestones: [
      { id: 'm17-1', name: 'Partner Feedback Collection', date: '2023-12-15', status: 'Completed' },
      { id: 'm17-2', name: 'Platform Build', date: '2024-04-30', status: 'Completed' },
      { id: 'm17-3', name: 'Go-Live', date: '2024-06-15', status: 'Completed' },
    ],
    lastUpdated: '2024-07-01',
    priority: 'High',
    portfolio: 'Business Development',
  },
  {
    id: 'proj-018',
    name: 'Momentum Sales Training',
    status: 'Planning',
    description: 'Develop and roll out a new sales training program for the global team.',
    startDate: '2024-09-15',
    endDate: '2025-03-15',
    budget: 150000,
    spent: 5000,
    completionPercentage: 3,
    teamLead: 'Rachel Berry',
    keyMilestones: [
      { id: 'm18-1', name: 'Curriculum Design', date: '2024-11-30', status: 'Pending' },
      { id: 'm18-2', name: 'Pilot Training Sessions', date: '2025-01-31', status: 'Pending' },
    ],
    lastUpdated: '2024-07-23',
    priority: 'Medium',
    portfolio: 'Business Development',
  },
  {
    id: 'proj-019',
    name: 'Starlight Cloud Cost Optimization',
    status: 'On Track',
    description: 'Identify and implement cloud cost optimization strategies across all services.',
    startDate: '2024-04-01',
    endDate: '2024-10-31',
    budget: 75000,
    spent: 25000,
    completionPercentage: 33,
    teamLead: 'Sam Winchester',
    keyMilestones: [
      { id: 'm19-1', name: 'Spending Analysis', date: '2024-05-31', status: 'Completed' },
      { id: 'm19-2', name: 'Optimization Plan Implementation', date: '2024-08-31', status: 'In Progress' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'Low',
    portfolio: 'Internal Tools',
  },
  {
    id: 'proj-020',
    name: 'Hyperion Enterprise Search',
    status: 'At Risk',
    description: 'Implement a new enterprise-wide search solution for documents and data.',
    startDate: '2024-03-01',
    endDate: '2024-11-30',
    budget: 450000,
    spent: 300000,
    completionPercentage: 50,
    teamLead: 'Dean Winchester',
    keyMilestones: [
      { id: 'm20-1', name: 'Vendor Selection', date: '2024-04-15', status: 'Completed' },
      { id: 'm20-2', name: 'Indexing Pilot Systems', date: '2024-07-31', status: 'In Progress' },
      { id: 'm20-3', name: 'Scalability Testing', date: '2024-09-30', status: 'Blocked' },
    ],
    lastUpdated: '2024-07-22',
    priority: 'High',
    portfolio: 'Data & Analytics',
  },
  {
    id: 'proj-021',
    name: 'Chronos Time Tracking Upgrade',
    status: 'Delayed',
    description: 'Upgrade the existing time tracking system with new features and integrations.',
    startDate: '2024-01-20',
    endDate: '2024-07-31', // Original end date, now delayed
    budget: 95000,
    spent: 90000,
    completionPercentage: 92,
    teamLead: 'Walter Bishop',
    keyMilestones: [
      { id: 'm21-1', name: 'Integration API Development', date: '2024-04-30', status: 'Completed' },
      { id: 'm21-2', name: 'Final UI Review', date: '2024-07-10', status: 'Completed' },
      { id: 'm21-3', name: 'Deployment to Production', date: '2024-07-25', status: 'In Progress' }, // Current step causing delay
    ],
    lastUpdated: '2024-07-24',
    priority: 'Low',
    portfolio: 'Internal Tools',
  },
  {
    id: 'proj-022',
    name: 'Polaris Customer Segmentation',
    status: 'Completed',
    description: 'Develop a new ML model for advanced customer segmentation.',
    startDate: '2023-12-01',
    endDate: '2024-06-15',
    budget: 180000,
    spent: 175000,
    completionPercentage: 100,
    teamLead: 'Fox Mulder',
    keyMilestones: [
      { id: 'm22-1', name: 'Data Preparation', date: '2024-02-01', status: 'Completed' },
      { id: 'm22-2', name: 'Model Training', date: '2024-04-15', status: 'Completed' },
      { id: 'm22-3', name: 'Validation and Deployment', date: '2024-06-01', status: 'Completed' },
    ],
    lastUpdated: '2024-06-20',
    priority: 'Medium',
    portfolio: 'Data & Analytics',
  },
  {
    id: 'proj-023',
    name: 'Argus Network Monitoring',
    status: 'On Track',
    description: 'Implement a next-gen network monitoring solution for proactive issue detection.',
    startDate: '2024-06-15',
    endDate: '2025-01-15',
    budget: 280000,
    spent: 40000,
    completionPercentage: 18,
    teamLead: 'Dana Scully',
    keyMilestones: [
      { id: 'm23-1', name: 'Sensor Deployment - Phase 1', date: '2024-08-31', status: 'In Progress' },
      { id: 'm23-2', name: 'Dashboard Configuration', date: '2024-10-31', status: 'Pending' },
    ],
    lastUpdated: '2024-07-23',
    priority: 'High',
    portfolio: 'Security Operations',
  },
  {
    id: 'proj-024',
    name: 'Elysium Employee Wellness Program',
    status: 'Planning',
    description: 'Launch a new company-wide employee wellness and mental health program.',
    startDate: '2024-11-01',
    endDate: '2025-04-30',
    budget: 120000,
    spent: 2000,
    completionPercentage: 1,
    teamLead: 'John Locke',
    keyMilestones: [
      { id: 'm24-1', name: 'Vendor Research & Selection', date: '2024-12-31', status: 'Pending' },
      { id: 'm24-2', name: 'Program Design & Communication Plan', date: '2025-02-15', status: 'Pending' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'Medium',
    portfolio: 'Human Capital',
  },
  {
    id: 'proj-025',
    name: 'Genesis Sustainable Packaging',
    status: 'On Track',
    description: 'Transition to 100% sustainable packaging for all product lines.',
    startDate: '2024-02-15',
    endDate: '2025-02-14',
    budget: 500000,
    spent: 180000,
    completionPercentage: 35,
    teamLead: 'Kate Austen',
    keyMilestones: [
      { id: 'm25-1', name: 'Material Sourcing & Testing', date: '2024-06-30', status: 'Completed' },
      { id: 'm25-2', name: 'Pilot Production Line Rollout', date: '2024-10-31', status: 'In Progress' },
    ],
    lastUpdated: '2024-07-21',
    priority: 'High',
    portfolio: 'Sustainability Goals',
  },
  {
    id: 'proj-026',
    name: 'Olympus Cloud Platform Migration',
    status: 'Delayed',
    description: 'Migrate remaining on-premise servers to Olympus Cloud Platform.',
    startDate: '2024-01-01',
    endDate: '2024-08-31',
    budget: 650000,
    spent: 550000,
    completionPercentage: 80,
    teamLead: 'James Sawyer',
    keyMilestones: [
      { id: 'm26-1', name: 'Application Compatibility Assessment', date: '2024-03-01', status: 'Completed' },
      { id: 'm26-2', name: 'Wave 1 Migration (Non-critical)', date: '2024-06-15', status: 'Completed' },
      { id: 'm26-3', name: 'Wave 2 Migration (Critical Systems)', date: '2024-08-15', status: 'In Progress' }, // Currently Delayed
    ],
    lastUpdated: '2024-07-25',
    priority: 'High',
    portfolio: 'Core Infrastructure',
  }
];


export function updateMockProject(updatedProject: Project): void {
  const projectIndex = mockProjects.findIndex(p => p.id === updatedProject.id);
  if (projectIndex !== -1) {
    mockProjects[projectIndex] = { ...updatedProject };
  } else {
    // Optionally handle case where project to update is not found
    console.warn(`Project with id ${updatedProject.id} not found for update.`);
    // mockProjects.push(updatedProject); // Or add if not found, depending on desired behavior
  }
}

// Available portfolios:
// Core Infrastructure
// Customer Experience
// Innovation Lab
// Research & Development (New)
// Security Operations (New)
// Sustainability Goals (New)
// Internal Tools (New)
// Data & Analytics (New)
// Business Development
// Human Capital
