
import type { Project } from '@/types/project';
import type { DiscussionComment } from '@/types/discussion';
import type { ProjectDocument } from '@/types/document';
import type { Resource, ResourceAllocation } from '@/types/resource';

export const mockResources: Resource[] = [
  { id: 'res-001', name: 'Alice Wonderland', type: 'Personnel', status: 'Partially Allocated', skills: ['Project Management', 'UX Design', 'Agile'], lastUpdated: '2024-07-28' },
  { id: 'res-002', name: 'Bob The Builder', type: 'Personnel', status: 'Fully Allocated', skills: ['Data Migration', 'Cloud Infrastructure', 'DevOps'], lastUpdated: '2024-07-28' },
  { id: 'res-003', name: 'Carol Danvers', type: 'Personnel', status: 'Partially Allocated', skills: ['AI Integration', 'CRM Systems', 'API Development'], lastUpdated: '2024-07-28' },
  { id: 'res-004', name: 'David Copperfield', type: 'Personnel', status: 'Available', skills: ['Security Audits', 'Protocol Implementation', 'Penetration Testing'], lastUpdated: '2024-07-28' },
  { id: 'res-005', name: 'Eva Green', type: 'Personnel', status: 'Partially Allocated', skills: ['Mobile Development', 'Market Research', 'Product Strategy'], lastUpdated: '2024-07-28' },
  { id: 'res-006', name: 'Frank Moses', type: 'Personnel', status: 'Available', skills: ['Marketing Strategy', 'Campaign Management', 'Creative Direction'], lastUpdated: '2024-07-28' },
  { id: 'res-007', name: 'Grace Hopper', type: 'Personnel', status: 'Available', skills: ['Quantum Computing', 'R&D', 'Algorithm Design'], lastUpdated: '2024-07-28' },
  { id: 'res-008', name: 'Harry Dresden', type: 'Personnel', status: 'Available', skills: ['Cybersecurity', 'Threat Modeling', 'Network Security'], lastUpdated: '2024-07-28' },
  { id: 'res-009', name: 'Ivy Valentine', type: 'Personnel', status: 'Available', skills: ['Supply Chain Optimization', 'Logistics', 'Vendor Management'], lastUpdated: '2024-07-28' },
  { id: 'res-010', name: 'Jack Sparrow', type: 'Personnel', status: 'Available', skills: ['HR Systems', 'Portal Development', 'User Experience'], lastUpdated: '2024-07-28' },
  { id: 'res-011', name: 'High-Performance Server Cluster', type: 'Equipment', status: 'Available', location: 'Data Center A', capacity: 10, notes: 'For compute-intensive tasks', lastUpdated: '2024-07-25' },
  { id: 'res-012', name: '3D Printer ProXL', type: 'Equipment', status: 'Maintenance', location: 'R&D Lab', notes: 'Scheduled maintenance until Aug 5th', lastUpdated: '2024-07-20' },
  { id: 'res-013', name: 'VR Development Kits (Set of 5)', type: 'Equipment', status: 'Partially Allocated', location: 'Innovation Hub', capacity: 5, lastUpdated: '2024-07-22' },
  { id: 'res-014', name: 'Conference Room Alpha', type: 'Facility', status: 'Available', location: 'Building 1, Floor 3', capacity: 20, lastUpdated: '2024-07-28' },
  { id: 'res-015', name: 'Mobile Testing Device Lab', type: 'Facility', status: 'Fully Allocated', location: 'Building 2, Floor 1', capacity: 8, notes: 'Includes various iOS and Android devices', lastUpdated: '2024-07-26' },
  { id: 'res-016', name: 'Charlie Brown', type: 'Personnel', status: 'Partially Allocated', skills: ['Frontend Development', 'JavaScript', 'React'], lastUpdated: '2024-07-28' },
  { id: 'res-017', name: 'Diana Prince', type: 'Personnel', status: 'Partially Allocated', skills: ['Backend Development', 'Java', 'Spring Boot'], lastUpdated: '2024-07-28' },
  { id: 'res-018', name: 'Edward Nygma', type: 'Personnel', status: 'Fully Allocated', skills: ['Database Administration', 'SQL', 'ETL Processes'], lastUpdated: '2024-07-28' },
  { id: 'res-019', name: 'Bruce Wayne', type: 'Personnel', status: 'Partially Allocated', skills: ['AI/ML Engineering', 'Python', 'TensorFlow'], lastUpdated: '2024-07-28' },
  { id: 'res-020', name: 'Selina Kyle', type: 'Personnel', status: 'Available', skills: ['Network Engineering', 'Cisco Certified', 'Firewall Management'], lastUpdated: '2024-07-28' },
  { id: 'res-021', name: 'Clark Kent', type: 'Personnel', status: 'Partially Allocated', skills: ['UI Design', 'Figma', 'Adobe XD'], lastUpdated: '2024-07-28' },
  { id: 'res-022', name: 'Lois Lane', type: 'Personnel', status: 'Available', skills: ['Content Creation', 'Copywriting', 'SEO'], lastUpdated: '2024-07-28' },
];

export const mockResourceAllocations: ResourceAllocation[] = [
  { id: 'alloc-001', projectId: 'proj-001', resourceId: 'res-001', startDate: '2024-01-15', endDate: '2024-12-20', effortPercentage: 70, role: 'Project Lead / UX' },
  { id: 'alloc-002', projectId: 'proj-001', resourceId: 'res-016', startDate: '2024-01-15', endDate: '2024-12-20', effortPercentage: 100, role: 'Lead Frontend Developer' },
  { id: 'alloc-003', projectId: 'proj-001', resourceId: 'res-017', startDate: '2024-01-15', endDate: '2024-12-20', effortPercentage: 80, role: 'Lead Backend Developer' },
  { id: 'alloc-004', projectId: 'proj-002', resourceId: 'res-002', startDate: '2024-03-01', endDate: '2024-09-30', effortPercentage: 100, role: 'Migration Lead' },
  { id: 'alloc-005', projectId: 'proj-002', resourceId: 'res-018', startDate: '2024-03-01', endDate: '2024-09-30', effortPercentage: 100, role: 'DBA & ETL Specialist' },
  { id: 'alloc-006', projectId: 'proj-003', resourceId: 'res-003', startDate: '2024-02-01', endDate: '2024-07-31', effortPercentage: 90, role: 'AI Integration Specialist' },
  { id: 'alloc-007', projectId: 'proj-003', resourceId: 'res-019', startDate: '2024-02-01', endDate: '2024-07-31', effortPercentage: 50, role: 'AI/ML Engineer' },
  { id: 'alloc-008', projectId: 'proj-005', resourceId: 'res-005', startDate: '2024-08-01', endDate: '2025-02-28', effortPercentage: 100, role: 'Mobile Project Lead' },
  { id: 'alloc-009', projectId: 'proj-005', resourceId: 'res-021', startDate: '2024-08-01', endDate: '2025-02-28', effortPercentage: 75, role: 'UI Designer' },
  { id: 'alloc-010', projectId: 'proj-011', resourceId: 'res-013', startDate: '2023-11-01', endDate: '2024-05-31', notes: '3 out of 5 kits used' }, // Equipment
  { id: 'alloc-011', projectId: 'proj-005', resourceId: 'res-015', startDate: '2024-09-01', endDate: '2025-02-28', notes: 'Full capacity booking for testing phase' }, // Facility
  { id: 'alloc-012', projectId: 'proj-006', resourceId: 'res-006', startDate: '2024-07-01', endDate: '2024-10-31', effortPercentage: 60, role: 'Campaign Manager' },
  { id: 'alloc-013', projectId: 'proj-006', resourceId: 'res-022', startDate: '2024-07-01', endDate: '2024-10-31', effortPercentage: 80, role: 'Content Lead' },
];


export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'Phoenix Initiative',
    status: 'On Track',
    description: 'A revolutionary new platform to integrate all enterprise services into a unified dashboard.',
    startDate: '2024-01-15',
    endDate: '2024-12-20',
    budget: 500000,
    spent: 120000,
    completionPercentage: 25,
    teamLead: 'Alice Wonderland', // res-001
    assignedUsers: ['Alice Wonderland', 'Charlie Brown', 'Diana Prince'],
    keyMilestones: [
      { id: 'm1-1', name: 'Initial Design Phase Complete', date: '2024-03-01', status: 'Completed', assignedTo: 'Alice Wonderland' },
      { id: 'm1-2', name: 'Alpha Version Release', date: '2024-06-15', status: 'In Progress', assignedTo: 'Charlie Brown' },
      { id: 'm1-3', name: 'Beta Testing', date: '2024-09-01', status: 'Pending', assignedTo: 'Diana Prince' },
    ],
    lastUpdated: '2024-07-20',
    priority: 'High',
    portfolio: 'Core Infrastructure',
    riskAssessment: undefined,
  },
  {
    id: 'proj-002',
    name: 'Orion Data Migration',
    status: 'At Risk',
    description: 'Migrate legacy customer data to the new cloud infrastructure with zero downtime.',
    startDate: '2024-03-01',
    endDate: '2024-09-30',
    budget: 250000,
    spent: 180000,
    completionPercentage: 60,
    teamLead: 'Bob The Builder', // res-002
    assignedUsers: ['Bob The Builder', 'Edward Nygma'],
    keyMilestones: [
      { id: 'm2-1', name: 'Infrastructure Setup', date: '2024-04-01', status: 'Completed', assignedTo: 'Bob The Builder' },
      { id: 'm2-2', name: 'Test Data Migration', date: '2024-06-01', status: 'Completed', assignedTo: 'Edward Nygma' },
      { id: 'm2-3', name: 'Production Data Migration Window 1', date: '2024-08-15', status: 'Blocked', assignedTo: 'Bob The Builder' },
    ],
    lastUpdated: '2024-07-18',
    priority: 'High',
    portfolio: 'Core Infrastructure',
    riskAssessment: {
        identifiedRisks: ["Potential data loss during migration", "Unexpected downtime exceeding SLA"],
        riskMitigationRecommendations: ["Perform incremental backups before migration", "Have rollback plan ready"],
        overallRiskScore: 75,
    }
  },
  {
    id: 'proj-003',
    name: 'Nebula AI Integration',
    status: 'Delayed',
    description: 'Integrate a third-party AI module for advanced analytics into the existing CRM.',
    startDate: '2024-02-01',
    endDate: '2024-07-31',
    budget: 150000,
    spent: 140000,
    completionPercentage: 85,
    teamLead: 'Carol Danvers', // res-003
    assignedUsers: ['Carol Danvers', 'Bruce Wayne'],
    keyMilestones: [
      { id: 'm3-1', name: 'API Key Acquisition', date: '2024-02-15', status: 'Completed', assignedTo: 'Carol Danvers'},
      { id: 'm3-2', name: 'Core Module Integration', date: '2024-05-01', status: 'Completed', assignedTo: 'Bruce Wayne' },
      { id: 'm3-3', name: 'User Acceptance Testing', date: '2024-07-15', status: 'In Progress', assignedTo: 'Carol Danvers' },
    ],
    lastUpdated: '2024-07-15',
    priority: 'Medium',
    portfolio: 'Customer Experience',
    riskAssessment: undefined,
  },
  {
    id: 'proj-004',
    name: 'Titan Security Overhaul',
    status: 'Completed',
    description: 'Comprehensive upgrade of all internal security protocols and systems.',
    startDate: '2023-09-01',
    endDate: '2024-03-31',
    budget: 300000,
    spent: 285000,
    completionPercentage: 100,
    teamLead: 'David Copperfield', // res-004
    assignedUsers: ['David Copperfield', 'Selina Kyle'],
    keyMilestones: [
      { id: 'm4-1', name: 'System Audit', date: '2023-10-01', status: 'Completed', assignedTo: 'David Copperfield' },
      { id: 'm4-2', name: 'Protocol Implementation', date: '2024-01-15', status: 'Completed', assignedTo: 'Selina Kyle' },
      { id: 'm4-3', name: 'Final Review & Sign-off', date: '2024-03-20', status: 'Completed', assignedTo: 'David Copperfield' },
    ],
    lastUpdated: '2024-04-01',
    priority: 'High',
    portfolio: 'Core Infrastructure',
    riskAssessment: {
        identifiedRisks: ["Initial vulnerabilities identified in audit"],
        riskMitigationRecommendations: ["All identified vulnerabilities patched and verified"],
        overallRiskScore: 15,
    }
  },
   {
    id: 'proj-005',
    name: 'Nova Mobile App',
    status: 'Planning',
    description: 'Develop a new cross-platform mobile application for customer engagement.',
    startDate: '2024-08-01',
    endDate: '2025-02-28',
    budget: 400000,
    spent: 10000,
    completionPercentage: 5,
    teamLead: 'Eva Green', // res-005
    assignedUsers: ['Eva Green', 'Clark Kent'],
    keyMilestones: [
      { id: 'm5-1', name: 'Market Research', date: '2024-08-30', status: 'In Progress', assignedTo: 'Eva Green' },
      { id: 'm5-2', name: 'UX/UI Design Specs', date: '2024-10-15', status: 'Pending', assignedTo: 'Clark Kent' },
    ],
    lastUpdated: '2024-07-19',
    priority: 'Medium',
    portfolio: 'Innovation Lab',
    riskAssessment: undefined,
  },
  {
    id: 'proj-006',
    name: 'Apollo Marketing Campaign',
    status: 'On Track',
    description: 'Launch a new marketing campaign for the Q4 product release.',
    startDate: '2024-07-01',
    endDate: '2024-10-31',
    budget: 120000,
    spent: 30000,
    completionPercentage: 20,
    teamLead: 'Frank Moses', // res-006
    assignedUsers: ['Frank Moses', 'Lois Lane'],
    keyMilestones: [
      { id: 'm6-1', name: 'Campaign Strategy Finalized', date: '2024-07-15', status: 'Completed', assignedTo: 'Frank Moses' },
      { id: 'm6-2', name: 'Creative Assets Production', date: '2024-08-30', status: 'In Progress', assignedTo: 'Lois Lane' },
      { id: 'm6-3', name: 'Campaign Launch', date: '2024-10-01', status: 'Pending', assignedTo: 'Frank Moses' },
    ],
    lastUpdated: '2024-07-22',
    priority: 'Medium',
    portfolio: 'Customer Experience',
    riskAssessment: undefined,
  },
  {
    id: 'proj-007',
    name: 'Quantum Leap Platform',
    status: 'Planning',
    description: 'Next-generation computing platform research and development.',
    startDate: '2024-09-01',
    endDate: '2026-08-31',
    budget: 1200000,
    spent: 50000,
    completionPercentage: 2,
    teamLead: 'Grace Hopper', // res-007
    assignedUsers: ['Grace Hopper', 'Ada Lovelace'],
    keyMilestones: [
      { id: 'm7-1', name: 'Feasibility Study', date: '2024-11-30', status: 'Pending', assignedTo: 'Grace Hopper' },
      { id: 'm7-2', name: 'Prototype Design', date: '2025-03-31', status: 'Pending', assignedTo: 'Ada Lovelace' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'High',
    portfolio: 'Research & Development',
  },
  {
    id: 'proj-008',
    name: 'CyberGuard Initiative',
    status: 'On Track',
    description: 'Enhance enterprise-wide cybersecurity posture against emerging threats.',
    startDate: '2024-05-15',
    endDate: '2025-01-31',
    budget: 350000,
    spent: 90000,
    completionPercentage: 30,
    teamLead: 'Harry Dresden', // res-008
    assignedUsers: ['Harry Dresden', 'Kevin Mitnick'],
    keyMilestones: [
      { id: 'm8-1', name: 'Threat Modeling', date: '2024-07-01', status: 'Completed', assignedTo: 'Harry Dresden' },
      { id: 'm8-2', name: 'Firewall Upgrades', date: '2024-09-15', status: 'In Progress', assignedTo: 'Kevin Mitnick' },
    ],
    lastUpdated: '2024-07-24',
    priority: 'High',
    portfolio: 'Security Operations',
  },
  {
    id: 'proj-009',
    name: 'EcoOptimize Supply Chain',
    status: 'At Risk',
    description: 'Optimize supply chain logistics for reduced carbon footprint and cost savings.',
    startDate: '2024-04-01',
    endDate: '2024-11-30',
    budget: 200000,
    spent: 150000,
    completionPercentage: 55,
    teamLead: 'Ivy Valentine', // res-009
    assignedUsers: ['Ivy Valentine', 'Greta Thunberg'],
    keyMilestones: [
      { id: 'm9-1', name: 'Current State Analysis', date: '2024-05-15', status: 'Completed', assignedTo: 'Ivy Valentine' },
      { id: 'm9-2', name: 'Vendor Negotiations', date: '2024-08-01', status: 'Blocked', assignedTo: 'Ivy Valentine' },
    ],
    lastUpdated: '2024-07-23',
    priority: 'Medium',
    portfolio: 'Sustainability Goals',
  },
  {
    id: 'proj-010',
    name: 'Zenith HR Portal',
    status: 'Delayed',
    description: 'Develop a new self-service portal for Human Resources.',
    startDate: '2024-01-10',
    endDate: '2024-08-30',
    budget: 180000,
    spent: 170000,
    completionPercentage: 90,
    teamLead: 'Jack Sparrow', // res-010
    assignedUsers: ['Jack Sparrow', 'Elizabeth Swann'],
    keyMilestones: [
      { id: 'm10-1', name: 'Requirements Gathering', date: '2024-02-28', status: 'Completed', assignedTo: 'Jack Sparrow' },
      { id: 'm10-2', name: 'Backend Development', date: '2024-06-15', status: 'Completed', assignedTo: 'Elizabeth Swann' },
      { id: 'm10-3', name: 'Frontend Polish', date: '2024-08-10', status: 'In Progress', assignedTo: 'Jack Sparrow' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'Low',
    portfolio: 'Internal Tools',
  },
  {
    id: 'proj-011',
    name: 'Vortex VR Training',
    status: 'Completed',
    description: 'Create VR training modules for new employee onboarding.',
    startDate: '2023-10-01',
    endDate: '2024-05-31',
    budget: 220000,
    spent: 215000,
    completionPercentage: 100,
    teamLead: 'Kara Thrace',
    assignedUsers: ['Kara Thrace', 'Lee Adama'],
    keyMilestones: [
      { id: 'm11-1', name: 'Scenario Design', date: '2023-11-15', status: 'Completed', assignedTo: 'Kara Thrace' },
      { id: 'm11-2', name: 'VR Development', date: '2024-03-01', status: 'Completed', assignedTo: 'Lee Adama' },
      { id: 'm11-3', name: 'Pilot Program', date: '2024-05-01', status: 'Completed', assignedTo: 'Kara Thrace' },
    ],
    lastUpdated: '2024-06-05',
    priority: 'Medium',
    portfolio: 'Innovation Lab',
  },
  {
    id: 'proj-012',
    name: 'Matrix Data Lakehouse',
    status: 'On Track',
    description: 'Build a centralized data lakehouse for advanced analytics and reporting.',
    startDate: '2024-06-01',
    endDate: '2025-03-31',
    budget: 600000,
    spent: 75000,
    completionPercentage: 15,
    teamLead: 'Luke Skywalker',
    assignedUsers: ['Luke Skywalker', 'Leia Organa', 'Han Solo'],
    keyMilestones: [
      { id: 'm12-1', name: 'Data Source Identification', date: '2024-07-31', status: 'In Progress', assignedTo: 'Leia Organa' },
      { id: 'm12-2', name: 'Schema Design', date: '2024-09-30', status: 'Pending', assignedTo: 'Han Solo' },
    ],
    lastUpdated: '2024-07-22',
    priority: 'High',
    portfolio: 'Data & Analytics',
  },
  {
    id: 'proj-013',
    name: 'Helios Solar Farm Integration',
    status: 'Planning',
    description: 'Integrate new solar farm output into the existing power grid.',
    startDate: '2024-10-01',
    endDate: '2025-06-30',
    budget: 750000,
    spent: 20000,
    completionPercentage: 3,
    teamLead: 'Maria Hill',
    assignedUsers: ['Maria Hill', 'Tony Stark'],
    keyMilestones: [
      { id: 'm13-1', name: 'Regulatory Approval', date: '2024-12-15', status: 'Pending', assignedTo: 'Maria Hill' },
      { id: 'm13-2', name: 'Grid Connection Study', date: '2025-02-28', status: 'Pending', assignedTo: 'Tony Stark' },
    ],
    lastUpdated: '2024-07-19',
    priority: 'High',
    portfolio: 'Sustainability Goals',
  },
  {
    id: 'proj-014',
    name: 'Aegis Compliance Audit Tool',
    status: 'On Track',
    description: 'Develop an automated tool for continuous compliance auditing.',
    startDate: '2024-03-15',
    endDate: '2024-10-31',
    budget: 190000,
    spent: 100000,
    completionPercentage: 50,
    teamLead: 'Nick Fury',
    assignedUsers: ['Nick Fury', 'Natasha Romanoff'],
    keyMilestones: [
      { id: 'm14-1', name: 'Framework Definition', date: '2024-05-01', status: 'Completed', assignedTo: 'Nick Fury' },
      { id: 'm14-2', name: 'Rule Engine Development', date: '2024-08-15', status: 'In Progress', assignedTo: 'Natasha Romanoff' },
    ],
    lastUpdated: '2024-07-24',
    priority: 'Medium',
    portfolio: 'Security Operations',
  },
  {
    id: 'proj-015',
    name: 'Odyssey Customer Journey Mapping',
    status: 'At Risk',
    description: 'Map and optimize the end-to-end customer journey across all touchpoints.',
    startDate: '2024-05-01',
    endDate: '2024-12-15',
    budget: 90000,
    spent: 70000,
    completionPercentage: 40,
    teamLead: 'Olivia Dunham',
    assignedUsers: ['Olivia Dunham', 'Philip Broyles'],
    keyMilestones: [
      { id: 'm15-1', name: 'Workshop Facilitation', date: '2024-06-30', status: 'Completed', assignedTo: 'Olivia Dunham' },
      { id: 'm15-2', name: 'Data Collection from Systems', date: '2024-09-01', status: 'Blocked', assignedTo: 'Philip Broyles' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'Medium',
    portfolio: 'Customer Experience',
  },
  {
    id: 'proj-016',
    name: 'Pathfinder R&D Automation',
    status: 'On Track',
    description: 'Automate repetitive tasks in the R&D lab environment.',
    startDate: '2024-02-01',
    endDate: '2024-09-30',
    budget: 280000,
    spent: 150000,
    completionPercentage: 65,
    teamLead: 'Peter Bishop',
    assignedUsers: ['Peter Bishop', 'Astrid Farnsworth'],
    keyMilestones: [
      { id: 'm16-1', name: 'Process Identification', date: '2024-03-15', status: 'Completed', assignedTo: 'Peter Bishop' },
      { id: 'm16-2', name: 'Robotics Integration', date: '2024-07-31', status: 'In Progress', assignedTo: 'Astrid Farnsworth' },
    ],
    lastUpdated: '2024-07-20',
    priority: 'Medium',
    portfolio: 'Research & Development',
  },
  {
    id: 'proj-017',
    name: 'Catalyst Partner Portal',
    status: 'Completed',
    description: 'Launch a new portal for B2B partners with enhanced features.',
    startDate: '2023-11-01',
    endDate: '2024-06-30',
    budget: 320000,
    spent: 310000,
    completionPercentage: 100,
    teamLead: 'Quinn Fabray',
    assignedUsers: ['Quinn Fabray', 'Santana Lopez'],
    keyMilestones: [
      { id: 'm17-1', name: 'Partner Feedback Collection', date: '2023-12-15', status: 'Completed', assignedTo: 'Quinn Fabray' },
      { id: 'm17-2', name: 'Platform Build', date: '2024-04-30', status: 'Completed', assignedTo: 'Santana Lopez' },
      { id: 'm17-3', name: 'Go-Live', date: '2024-06-15', status: 'Completed', assignedTo: 'Quinn Fabray' },
    ],
    lastUpdated: '2024-07-01',
    priority: 'High',
    portfolio: 'Business Development',
  },
  {
    id: 'proj-018',
    name: 'Momentum Sales Training',
    status: 'Planning',
    description: 'Develop and roll out a new sales training program for the global team.',
    startDate: '2024-09-15',
    endDate: '2025-03-15',
    budget: 150000,
    spent: 5000,
    completionPercentage: 3,
    teamLead: 'Rachel Berry',
    assignedUsers: ['Rachel Berry', 'Finn Hudson'],
    keyMilestones: [
      { id: 'm18-1', name: 'Curriculum Design', date: '2024-11-30', status: 'Pending', assignedTo: 'Rachel Berry' },
      { id: 'm18-2', name: 'Pilot Training Sessions', date: '2025-01-31', status: 'Pending', assignedTo: 'Finn Hudson' },
    ],
    lastUpdated: '2024-07-23',
    priority: 'Medium',
    portfolio: 'Business Development',
  },
  {
    id: 'proj-019',
    name: 'Starlight Cloud Cost Optimization',
    status: 'On Track',
    description: 'Identify and implement cloud cost optimization strategies across all services.',
    startDate: '2024-04-01',
    endDate: '2024-10-31',
    budget: 75000,
    spent: 25000,
    completionPercentage: 33,
    teamLead: 'Sam Winchester',
    assignedUsers: ['Sam Winchester', 'Bobby Singer'],
    keyMilestones: [
      { id: 'm19-1', name: 'Spending Analysis', date: '2024-05-31', status: 'Completed', assignedTo: 'Sam Winchester' },
      { id: 'm19-2', name: 'Optimization Plan Implementation', date: '2024-08-31', status: 'In Progress', assignedTo: 'Bobby Singer' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'Low',
    portfolio: 'Internal Tools',
  },
  {
    id: 'proj-020',
    name: 'Hyperion Enterprise Search',
    status: 'At Risk',
    description: 'Implement a new enterprise-wide search solution for documents and data.',
    startDate: '2024-03-01',
    endDate: '2024-11-30',
    budget: 450000,
    spent: 300000,
    completionPercentage: 50,
    teamLead: 'Dean Winchester',
    assignedUsers: ['Dean Winchester', 'Castiel'],
    keyMilestones: [
      { id: 'm20-1', name: 'Vendor Selection', date: '2024-04-15', status: 'Completed', assignedTo: 'Dean Winchester' },
      { id: 'm20-2', name: 'Indexing Pilot Systems', date: '2024-07-31', status: 'In Progress', assignedTo: 'Castiel' },
      { id: 'm20-3', name: 'Scalability Testing', date: '2024-09-30', status: 'Blocked', assignedTo: 'Dean Winchester' },
    ],
    lastUpdated: '2024-07-22',
    priority: 'High',
    portfolio: 'Data & Analytics',
  },
  {
    id: 'proj-021',
    name: 'Chronos Time Tracking Upgrade',
    status: 'Delayed',
    description: 'Upgrade the existing time tracking system with new features and integrations.',
    startDate: '2024-01-20',
    endDate: '2024-07-31', // Original end date, now delayed
    budget: 95000,
    spent: 90000,
    completionPercentage: 92,
    teamLead: 'Walter Bishop',
    assignedUsers: ['Walter Bishop', 'Nina Sharp'],
    keyMilestones: [
      { id: 'm21-1', name: 'Integration API Development', date: '2024-04-30', status: 'Completed', assignedTo: 'Walter Bishop' },
      { id: 'm21-2', name: 'Final UI Review', date: '2024-07-10', status: 'Completed', assignedTo: 'Nina Sharp' },
      { id: 'm21-3', name: 'Deployment to Production', date: '2024-07-25', status: 'In Progress', assignedTo: 'Walter Bishop' },
    ],
    lastUpdated: '2024-07-24',
    priority: 'Low',
    portfolio: 'Internal Tools',
  },
  {
    id: 'proj-022',
    name: 'Polaris Customer Segmentation',
    status: 'Completed',
    description: 'Develop a new ML model for advanced customer segmentation.',
    startDate: '2023-12-01',
    endDate: '2024-06-15',
    budget: 180000,
    spent: 175000,
    completionPercentage: 100,
    teamLead: 'Fox Mulder',
    assignedUsers: ['Fox Mulder', 'The Lone Gunmen'],
    keyMilestones: [
      { id: 'm22-1', name: 'Data Preparation', date: '2024-02-01', status: 'Completed', assignedTo: 'The Lone Gunmen' },
      { id: 'm22-2', name: 'Model Training', date: '2024-04-15', status: 'Completed', assignedTo: 'Fox Mulder' },
      { id: 'm22-3', name: 'Validation and Deployment', date: '2024-06-01', status: 'Completed', assignedTo: 'Fox Mulder' },
    ],
    lastUpdated: '2024-06-20',
    priority: 'Medium',
    portfolio: 'Data & Analytics',
  },
  {
    id: 'proj-023',
    name: 'Argus Network Monitoring',
    status: 'On Track',
    description: 'Implement a next-gen network monitoring solution for proactive issue detection.',
    startDate: '2024-06-15',
    endDate: '2025-01-15',
    budget: 280000,
    spent: 40000,
    completionPercentage: 18,
    teamLead: 'Dana Scully',
    assignedUsers: ['Dana Scully', 'Walter Skinner'],
    keyMilestones: [
      { id: 'm23-1', name: 'Sensor Deployment - Phase 1', date: '2024-08-31', status: 'In Progress', assignedTo: 'Walter Skinner' },
      { id: 'm23-2', name: 'Dashboard Configuration', date: '2024-10-31', status: 'Pending', assignedTo: 'Dana Scully' },
    ],
    lastUpdated: '2024-07-23',
    priority: 'High',
    portfolio: 'Security Operations',
  },
  {
    id: 'proj-024',
    name: 'Elysium Employee Wellness Program',
    status: 'Planning',
    description: 'Launch a new company-wide employee wellness and mental health program.',
    startDate: '2024-11-01',
    endDate: '2025-04-30',
    budget: 120000,
    spent: 2000,
    completionPercentage: 1,
    teamLead: 'John Locke',
    assignedUsers: ['John Locke', 'Benjamin Linus'],
    keyMilestones: [
      { id: 'm24-1', name: 'Vendor Research & Selection', date: '2024-12-31', status: 'Pending', assignedTo: 'John Locke' },
      { id: 'm24-2', name: 'Program Design & Communication Plan', date: '2025-02-15', status: 'Pending', assignedTo: 'Benjamin Linus' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'Medium',
    portfolio: 'Human Capital',
  },
  {
    id: 'proj-025',
    name: 'Genesis Sustainable Packaging',
    status: 'On Track',
    description: 'Transition to 100% sustainable packaging for all product lines.',
    startDate: '2024-02-15',
    endDate: '2025-02-14',
    budget: 500000,
    spent: 180000,
    completionPercentage: 35,
    teamLead: 'Kate Austen',
    assignedUsers: ['Kate Austen', 'Hugo Reyes'],
    keyMilestones: [
      { id: 'm25-1', name: 'Material Sourcing & Testing', date: '2024-06-30', status: 'Completed', assignedTo: 'Kate Austen' },
      { id: 'm25-2', name: 'Pilot Production Line Rollout', date: '2024-10-31', status: 'In Progress', assignedTo: 'Hugo Reyes' },
    ],
    lastUpdated: '2024-07-21',
    priority: 'High',
    portfolio: 'Sustainability Goals',
  },
  {
    id: 'proj-026',
    name: 'Olympus Cloud Platform Migration',
    status: 'Delayed',
    description: 'Migrate remaining on-premise servers to Olympus Cloud Platform.',
    startDate: '2024-01-01',
    endDate: '2024-08-31',
    budget: 650000,
    spent: 550000,
    completionPercentage: 80,
    teamLead: 'James Sawyer',
    assignedUsers: ['James Sawyer', 'Juliet Burke'],
    keyMilestones: [
      { id: 'm26-1', name: 'Application Compatibility Assessment', date: '2024-03-01', status: 'Completed', assignedTo: 'James Sawyer' },
      { id: 'm26-2', name: 'Wave 1 Migration (Non-critical)', date: '2024-06-15', status: 'Completed', assignedTo: 'Juliet Burke' },
      { id: 'm26-3', name: 'Wave 2 Migration (Critical Systems)', date: '2024-08-15', status: 'In Progress', assignedTo: 'James Sawyer' },
    ],
    lastUpdated: '2024-07-25',
    priority: 'High',
    portfolio: 'Core Infrastructure',
  }
];


export const mockDiscussions: DiscussionComment[] = [
  {
    id: 'disc1-proj001',
    projectId: 'proj-001',
    author: 'Alice Wonderland',
    authorAvatar: 'https://picsum.photos/seed/alice/40',
    timestamp: '2024-07-20T10:00:00Z',
    content: 'Alpha release is looking good. Let\'s focus on performance improvements for the next sprint.',
  },
  {
    id: 'disc2-proj001',
    projectId: 'proj-001',
    author: 'Charlie Brown',
    authorAvatar: 'https://picsum.photos/seed/charlie/40',
    timestamp: '2024-07-20T10:30:00Z',
    content: 'Agreed. I\'ve identified a few bottlenecks in the data processing module. Will create tasks for these.',
  },
  {
    id: 'disc1-proj002',
    projectId: 'proj-002',
    author: 'Bob The Builder',
    authorAvatar: 'https://picsum.photos/seed/bob/40',
    timestamp: '2024-07-18T14:00:00Z',
    content: 'Production migration window 1 is blocked due to unexpected dependencies. We need to escalate this.',
  },
];

export const mockDocuments: ProjectDocument[] = [
  {
    id: 'doc1-proj001',
    projectId: 'proj-001',
    name: 'Project Phoenix - Initial PRD.pdf',
    type: 'PDF',
    size: '2.5MB',
    uploadedAt: '2024-01-20T09:00:00Z',
    uploadedBy: 'Alice Wonderland',
    url: '#',
  },
  {
    id: 'doc2-proj001',
    projectId: 'proj-001',
    name: 'Alpha Release Test Plan.docx',
    type: 'Word',
    size: '850KB',
    uploadedAt: '2024-06-01T11:30:00Z',
    uploadedBy: 'Charlie Brown',
    url: '#',
  },
  {
    id: 'doc1-proj002',
    projectId: 'proj-002',
    name: 'Data Migration Strategy.pptx',
    type: 'PowerPoint',
    size: '5.1MB',
    uploadedAt: '2024-03-05T16:15:00Z',
    uploadedBy: 'Bob The Builder',
    url: '#',
  },
  {
    id: 'doc2-proj002',
    projectId: 'proj-002',
    name: 'Rollback_Procedure_v3.pdf',
    type: 'PDF',
    size: '1.2MB',
    uploadedAt: '2024-07-10T09:00:00Z',
    uploadedBy: 'Edward Nygma',
    url: '#',
  }
];


export function updateMockProject(updatedProject: Project): void {
  const projectIndex = mockProjects.findIndex(p => p.id === updatedProject.id);
  if (projectIndex !== -1) {
    mockProjects[projectIndex] = { ...updatedProject };
  } else {
    console.warn(`Project with id ${updatedProject.id} not found for update.`);
  }
}

export function addMockDiscussionComment(projectId: string, comment: Omit<DiscussionComment, 'id' | 'projectId' | 'timestamp' | 'authorAvatar'>, authorUsername: string): DiscussionComment {
  const newComment: DiscussionComment = {
    ...comment,
    id: `disc${Date.now()}-${projectId}`,
    projectId,
    timestamp: new Date().toISOString(),
    author: authorUsername,
    authorAvatar: `https://picsum.photos/seed/${authorUsername.replace(/\s+/g, '')}/40`,
  };
  mockDiscussions.push(newComment);
  return newComment;
}

export function addMockDocument(projectId: string, document: Omit<ProjectDocument, 'id' | 'projectId' | 'uploadedAt' | 'url' | 'type'>, uploadedByUsername: string, type: ProjectDocument['type'] = 'Other' ): ProjectDocument {
  const newDocument: ProjectDocument = {
    ...document,
    id: `doc${Date.now()}-${projectId}`,
    projectId,
    type,
    uploadedAt: new Date().toISOString(),
    uploadedBy: uploadedByUsername,
    url: '#', // Placeholder URL
  };
  mockDocuments.push(newDocument);
  return newDocument;
}

// Available portfolios:
// Core Infrastructure
// Customer Experience
// Innovation Lab
// Research & Development
// Security Operations
// Sustainability Goals
// Internal Tools
// Data & Analytics
// Business Development
// Human Capital
// Finance Modernization
// Global Expansion
// Product Lifecycle Management
// Digital Transformation
// Operational Excellence
